accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"

urlpatterns = [
    path('login/',  views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('register/', views.register_user, name="register"),
    path('profile/', views.profile, name="profile"),
]

djauth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
]

accounts/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterUserForm(UserCreationForm):
    email = forms.CharField(min_length=5, max_length=120)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    email.widget.attrs['class'] = 'form-control'
    email.widget.attrs['placeholder'] = 'Enter your email'
    email.label = 'Email' 
    email.help_text= ''# '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

    def __init__ (self,  *args, **kwargs):
        super(RegisterUserForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['username'].label = 'User Name'
        self.fields['username'].help_text = ''# '<span class="form-text text-muted"><small>Required. </small></span>'

        
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password1'].label = 'Password'
        self.fields['password1'].help_text = ''

        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
        self.fields['password2'].label = 'Confirm password'
        self.fields['password2'].help_text = ''

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import RegisterUserForm

# Create your views here.
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        psw = request.POST.get('password')

        user = authenticate(username=username, password=psw)
        if user is not None:
            print("KNOWN USER")
            login(request, user)
            print("USER LOGGED IN, redirect")
            return redirect('accounts:profile')
        else:
            messages.error(request, ('Invalid credentials'))

    return render(request, 'accounts/login.html')

def logout_user(request):
    logout(request)
    return redirect('main:index')


def register_user(request):
    if request.method == 'POST':
        form = RegisterUserForm(request.POST)
       
        if form.is_valid():
            form.save()
            user = authenticate(username=form.cleaned_data.get('username'), password=form.cleaned_data.get('password1'))
            return redirect('accounts:login')
    else:
        form = RegisterUserForm()

    return render(request, 'accounts/register.html', {'form': form})

@login_required
def profile(request):
    return render(request, 'accounts/profile.html')

main/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "main/index.html", {})

def about(request):
    return render(request, "main/about.html")

templates/accounts/login.html
 {% extends "base.html" %}

 {% block content%}
    <div class="col-6 col-md-4">
    {% if messages%}
        {% for message in messages%}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>{{message }}</strong> 
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
        <h2>Login</h2>
        <form method="post">
           {% csrf_token %}
            <div class="mb-3">
                <label for="username" class="form-label">Username</label>
                <input type="text" class="form-control" id="username" name="username">
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <input type="password" class="form-control" id="password" name="password">
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
 {% endblock %}

templates/accounts/profile.html
{% extends "base.html" %}

{% block content %}
    <h2>Profile {{request.user.username}}</h2>
{% endblock %}

templates/accounts/register.html
{% extends "base.html" %}

{% block content%}

<style>
.errorlist
    {
        color: red;
    }
    </style>
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
            <div class="card-body">
                <h5 class="card-title text-center mb-3">Register for new account, it's free!</h5>
                <hr class="my-4">
                <form class="form-signin" method="post" action="{% url 'accounts:register' %}">
                    {% csrf_token %}
                    {% if form.errors %}
                   <div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
                    <strong>Form contains errors!</strong> <br>Correct them and try again.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>

                    {% endif %}
                    {{ form.as_p }}
                    {% comment %} <div class="form-label-group m-2">
                        <input type="text" id="username" class="form-control " placeholder="Username" required autofocus
                            name="username">
                    </div>


                    <div class="form-label-group m-2">
                        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required
                            autofocus name="email">
                    </div>

                    <div class="form-label-group m-2">
                        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required
                            name="password1">
                        {{ form.password1.errors }}

                    </div>

                    <div class="form-label-group m-2">
                        <input type="password" id="inputPassword" class="form-control" placeholder="Confirm Password"
                            required name="password2">
                        {{ form.password2.errors }}
                    </div>

                    {% endcomment %}
                    <button class="btn btn-primary btn-block text-uppercase m-2" type="submit">Sign in</button>
                    <hr class="my-4">
                </form>
            </div>
        </div>  
    </div>
</div>
 <script>

    window.setTimeout(function() {
        $(".alert").hide();
        }, 3000);
  </script>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="de">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
 
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'main:index'%}">Auth Example</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'main:index'%}">Home</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'main:about'%}">About</a>
        </li>
        {% if request.user.is_authenticated %}
         <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'accounts:profile'%}">Profile</a>
        </li>
        {% endif %}
      </ul>
      <div class="my-2 my-lg-0">
   
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:profile'%}">Hello {{request.user.username}}</a>
      </li>
       <li class="nav-item">
           <a class="nav-link " href="{% url 'accounts:logout' %}"> Logout</a>
        </li>
      {% else %}
        <li class="nav-item">
            <a class="nav-link " href="{% url 'accounts:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:register'%}">Register</a>
        </li>
      {% endif %}
        
       </ul>
      </div>
      
     
    </div>
  </div>
</nav>
    {% block content %}
    {% endblock %}


    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  
  </body>
</html>

templates/main/about.html
{% extends "base.html" %}

{% block content %}
<h1>This is the about page </h1>
{% endblock %}

templates/main/index.html
{% extends "base.html" %}

{% block content %}
<h1>This is the index page </h1>
{% endblock %}